version: "3.8"
services:
  backend:
    build:
      context: ./BooksReviewGen
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
