version: "3.8"
services:
  backend:
    build:
      context: ./BooksReviewGen
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
